{
  "formatVersion": "1.1",
  "component": {
    "group": "me.aagaming",
    "module": "fast-load-plugin",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fast-load-plugin-0.1.3.jar",
          "url": "fast-load-plugin-0.1.3.jar",
          "size": 20461,
          "sha512": "70a5d4773027a8a3d15d877713fdd8643afcfac36fd03c624d8f69e7e8303d63d1422954aaca9ae0f6dad1260d23988cf09c3301f6733374d0fd6448be62ea21",
          "sha256": "f59e9bc215cddca02d448ea4f4779d79418191cb68c221550f3529801e7a9b60",
          "sha1": "9cb90aa02257ca06f7471db4b69573f7c786b790",
          "md5": "db2b4a18bbc06ddc3b1fd08ae432da55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "fast-load-plugin-0.1.3.jar",
          "url": "fast-load-plugin-0.1.3.jar",
          "size": 20461,
          "sha512": "70a5d4773027a8a3d15d877713fdd8643afcfac36fd03c624d8f69e7e8303d63d1422954aaca9ae0f6dad1260d23988cf09c3301f6733374d0fd6448be62ea21",
          "sha256": "f59e9bc215cddca02d448ea4f4779d79418191cb68c221550f3529801e7a9b60",
          "sha1": "9cb90aa02257ca06f7471db4b69573f7c786b790",
          "md5": "db2b4a18bbc06ddc3b1fd08ae432da55"
        }
      ]
    }
  ]
}
